force-app/main/default/objects/Lead_Request__c/Lead_Request__c.object-meta.xml
<CustomObject>
    <label>Lead Request</label>
    <nameField>
        <label>Lead Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CleanupLeadRequestsBatch.cls
global class CleanupLeadRequestsBatch implements Database.Batchable<sObject> {
  global Database.QueryLocator start(Database.BatchableContext bc) {
    String query =
      'SELECT Id FROM Lead_Request__c ' +
      'WHERE Request_Status__c = \'Converted\' ' +
      'AND Conversion_Date__c < LAST_N_DAYS:730';
    return Database.getQueryLocator(query);
  }

  global void execute(
    Database.BatchableContext bc,
    List<Lead_Request__c> scope
  ) {
    delete as user scope; // TODO empty recycle bin
  }

  global void finish(Database.BatchableContext bc) {
  }
}